# Permalinks
permalink:      /:year-:month-:day/:title

# Setup
title:          googie
baseurl:        ""
# url:            "https://www.jihyeleee.com"

# Assets
sass:
  sass_dir:     _sass
  style:        :compressed

# Build settings
markdown:       kramdown

# About
author:
  name:         googie
  # url:          https://jihyeleee.com/
  email:        googieyu@gmail.com
  github:       googie94
  # twitter:      

# Custom vars
# version:        3.4.1
# github:
  # repo:         https://github.com/googie94/