# Permalinks
permalink:      /:year-:month-:day/:title

# Setup
title:          googie
baseurl:        ""

# Assets
sass:
  sass_dir:     _sass
  style:        :compressed

# Build settings
markdown:       kramdown

# About
author:
  name:         googie
  email:        googieyu@gmail.com
  github:       googie94

# discus
discus-identifier: googie

# script - chart
head_scripts:
  - https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.7.2/Chart.min.js

# Custom vars
# version:        3.4.1
# github:
  # repo:         https://github.com/googie94/